# Generated by Django 6.0.3 on 2026-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_is_expiring_soon_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fines',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
